POST http://localhost:3003/api/blogs
Content-Type: application/json

{
	"title": "Frogs are evil",
	"author": "doodman the great",
	"url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify",
	"likes": 2
}